# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Khoa Dinh
tagline:          Blog
url:              http://khoadinh.github.io
paginate:         1
baseurl:          /
author:
  name:           Khoa Dinh
  url:            https://twitter.com/khoadinh290
  email:          khoadinh290@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/khoadinh/khoadinh.github.io
